// Dependency-free fallback acceptance runner against Vite's actual transformed game modules.
// This supplements, and does not replace, Vitest and the TypeScript build.
import {mkdtemp,writeFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const out=await mkdtemp(join(tmpdir(),'infra-rush-logic-'));
const master={};for(const name of ['game','resources','bots','castle','bridges','tasks','earthquake','vehicles','cpu'])master[name]=JSON.parse(await readFile(`master/${name}.json`,'utf8'));
await writeFile(join(out,'master.mjs'),`export const M=${JSON.stringify(master)};`);
for(const name of ['engine','cpu']){const response=await fetch(`http://localhost:5173/src/game/${name}.ts`);assert.equal(response.status,200);let code=await response.text();code=code.replace(/from "\/src\/game\/master\.ts(?:\?[^"]*)?"/g,'from "./master.mjs"').replace(/from "\/src\/game\/engine\.ts(?:\?[^"]*)?"/g,'from "./engine.mjs"');await writeFile(join(out,`${name}.mjs`),code);}
const {createGame,command,tick,earthquake}=await import(pathToFileURL(join(out,'engine.mjs')));const {CPU}=await import(pathToFileURL(join(out,'cpu.mjs')));
const step=(s,t)=>{for(let i=0;i<Math.ceil(t/.05);i++)tick(s,.05)};const results=[];const check=(name,f)=>{f();results.push({name,passed:true});console.log('PASS '+name)};
const funded=()=>{const s=createGame(123);s.nextQuake=1000;for(const t of ['blue','red'])s.teams[t].resources={soil:500,stone:500,iron:500};return s};
const task=(s,action,target='blue',team='blue')=>{assert.equal(command(s,team,{botId:team+'-0',action,target}).ok,true);step(s,35)};
check('five Bots, zero starting resources and castle HP5',()=>{const s=createGame();assert.equal(s.bots.length,10);assert.deepEqual(s.teams.blue.resources,{soil:0,stone:0,iron:0});assert.equal(s.teams.blue.hp,5)});
check('mining -> resources -> bridge -> attack -> return',()=>{const s=createGame(123);s.nextQuake=1000;for(let i=0;i<5;i++)command(s,'blue',{botId:`blue-${i}`,action:'mine'});step(s,32);assert(s.teams.blue.resources.stone>=50);assert(s.teams.blue.resources.iron>0);task(s,'build');assert.equal(s.bridges[0].level,1);task(s,'march');assert.equal(s.teams.red.hp,4);assert.equal(s.bots[0].state,'IDLE');assert.deepEqual(s.bots[0].position,s.bots[0].home)});
check('resource payment is atomic and duplicate construction rejected',()=>{const s=funded();command(s,'blue',{botId:'blue-0',action:'build',target:'blue'});assert.equal(command(s,'blue',{botId:'blue-1',action:'build',target:'blue'}).ok,false);assert.equal(s.teams.blue.resources.stone,450);assert.equal(command(s,'blue',{botId:'blue-0',action:'cancel'}).ok,false)});
check('bridge upgrades, enemy drill, repair and resource costs',()=>{const s=funded();task(s,'build');task(s,'upgrade');task(s,'upgrade');assert.equal(s.bridges[0].level,3);task(s,'destroy','blue','red');assert.equal(s.bridges[0].level,2);task(s,'repair');assert.equal(s.bridges[0].level,3);assert.equal(s.bridges[0].damage,0);assert.equal(s.teams.blue.resources.iron,390)});
check('embankment interrupts march; clearing restores route',()=>{const s=funded();task(s,'build');task(s,'embank','blue','red');assert.equal(command(s,'blue',{botId:'blue-0',action:'march'}).ok,false);task(s,'clear');assert.equal(s.bridges[0].blockedBy,null);command(s,'blue',{botId:'blue-0',action:'march'});step(s,2);s.bridges[0].blockedBy='red';step(s,20);assert.equal(s.teams.red.hp,5);assert.equal(s.bots[0].state,'IDLE')});
check('central bridge prerequisite, ownership and neutralization',()=>{const s=funded();assert.equal(command(s,'blue',{botId:'blue-0',action:'build',target:'center'}).ok,false);task(s,'build');task(s,'build','red','red');task(s,'build','center');task(s,'destroy','center','red');assert.equal(s.bridges[1].owner,null);task(s,'build','center','red');assert.equal(s.bridges[1].owner,'red')});
check('five simultaneous marches decide victory exactly at HP0',()=>{const s=funded();task(s,'build');for(let i=0;i<5;i++)command(s,'blue',{botId:`blue-${i}`,action:'march'});step(s,25);assert.equal(s.winner,'blue');assert.equal(s.teams.red.hp,0);assert.equal(s.teams.blue.stats.attacks,5)});
check('earthquakes never collapse bridges, timeout is draw',()=>{const s=funded();task(s,'build');for(let i=0;i<30;i++)earthquake(s);assert.equal(s.bridges[0].level,1);step(s,360);assert.equal(s.winner,'draw')});
const matches=[];check('30 seeded CPU games finish with valid resources and legal construction',()=>{for(let seed=0;seed<30;seed++){const s=createGame(seed),blue=new CPU('normal','blue'),red=new CPU('hard','red');for(let i=0;i<7300&&s.status==='playing';i++){blue.update(s);red.update(s);tick(s,.05)}assert.equal(s.status,'finished');for(const team of ['blue','red']){assert(s.teams[team].stats.built>0);assert(Object.values(s.teams[team].resources).every(x=>x>=0))}matches.push({seed,winner:s.winner,time:s.time,blue:s.teams.blue.stats,red:s.teams.red.stats})}});
await writeFile('docs/qa/logic-smoke-results.json',JSON.stringify({results,matches},null,2));console.log(`All ${results.length} acceptance checks passed`);
